<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="rupesh" failures="1" tests="1" name="Add_Cluster_Test" time="137.281" errors="0" timestamp="26 Mar 2020 08:45:00 GMT">
  <testcase classname="com.dataseers.qa.testcases.AddCluster_Test" name="Add_NewCluster_Test" time="132.874">
    <failure type="java.lang.AssertionError" message="Save new cluster scenario failed">
      <![CDATA[java.lang.AssertionError: Save new cluster scenario failed
	at com.dataseers.qa.pages.Administration_Module.ds_Cluster_Mgmt_Page.savecluster(ds_Cluster_Mgmt_Page.java:299)
	at com.dataseers.qa.testcases.AddCluster_Test.Add_NewCluster_Test(AddCluster_Test.java:60)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Add_NewCluster_Test -->
</testsuite> <!-- Add_Cluster_Test -->
