<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="rupesh" failures="1" tests="1" name="Add_User_Test" time="36.431" errors="0" timestamp="22 Apr 2020 07:44:31 GMT">
  <testcase classname="com.dataseers.qa.testcases.AddUser_Test" name="Add_NewUser_Test" time="29.817">
    <failure type="java.lang.AssertionError" message="Save new user scenario failed">
      <![CDATA[java.lang.AssertionError: Save new user scenario failed
	at com.dataseers.qa.pages.administration.UserMgmt.saveuser(UserMgmt.java:262)
	at com.dataseers.qa.testcases.AddUser_Test.Add_NewUser_Test(AddUser_Test.java:64)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Add_NewUser_Test -->
</testsuite> <!-- Add_User_Test -->
