<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="rupesh" failures="1" tests="1" name="com.dataseers.qa.testcases.RealTimeAccountHolder_Test1" time="14.500" errors="0" timestamp="7 Jul 2020 11:22:41 GMT">
  <testcase classname="com.dataseers.qa.testcases.RealTimeAccountHolder_Test1" name="RalTime_AccountHolder_Test" time="14.500">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at com.dataseers.qa.pages.reports.realtimemesseges.reportsAPItest.accountHolderAPITest(reportsAPItest.java:220)
	at com.dataseers.qa.pages.reports.realtimemesseges.AccountHolderPage.reportsModule(AccountHolderPage.java:114)
	at com.dataseers.qa.pages.reports.realtimemesseges.AccountHolderPage.realTimeMsgPage(AccountHolderPage.java:129)
	at com.dataseers.qa.pages.reports.realtimemesseges.AccountHolderPage.searchDetails(AccountHolderPage.java:152)
	at com.dataseers.qa.testcases.RealTimeAccountHolder_Test1.RalTime_AccountHolder_Test(RealTimeAccountHolder_Test1.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- RalTime_AccountHolder_Test -->
</testsuite> <!-- com.dataseers.qa.testcases.RealTimeAccountHolder_Test1 -->
